spring:
  application:
    name: medicenter

  datasource:
    url: jdbc:sqlserver://DESKTOP-NFS1S87\SQLEXPRESS:1433;databaseName=MedicenterDB;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
